[workspace]
members = [
  "packages/utils",
  "packages/contracts/mock/api",
  "packages/contracts/mock/service-handler",
  "packages/contracts/mock/service-manager",
  "packages/contracts/mock/trigger",
  "packages/contracts/ecdsa/api",
  "packages/contracts/ecdsa/service-handler",
  "packages/contracts/ecdsa/service-manager",
  "packages/contracts/bls/api",
  "packages/contracts/bls/service-handler",
  "packages/contracts/bls/service-manager",
  "packages/components/echo-with-id",
  "packages/tests/off-chain",
  "packages/tests/on-chain",
  "packages/tests/shared",
  "packages/cli",
]

resolver = "2"

[workspace.package]
edition = "2021"
version = "0.5.3"
license = "GPL-3.0-or-later"
authors = ["Layer Labs (Cayman)"]
repository = "https://github.com/Lay3rLabs/cw-middleware"
rust-version = "1.88.0"

[workspace.dependencies]
# Local
mock-api = { path = "packages/contracts/mock/api" }
ecdsa-api = { path = "packages/contracts/ecdsa/api" }
bls-api = { path = "packages/contracts/bls/api" }
utils = { path = "packages/utils" }
mock-service-handler = { path = "packages/contracts/mock/service-handler" }
mock-service-manager = { path = "packages/contracts/mock/service-manager" }
mock-trigger = { path = "packages/contracts/mock/trigger" }
ecdsa-service-handler = { path = "packages/contracts/ecdsa/service-handler" }
ecdsa-service-manager = { path = "packages/contracts/ecdsa/service-manager" }
bls-service-handler = { path = "packages/contracts/bls/service-handler" }
bls-service-manager = { path = "packages/contracts/bls/service-manager" }
shared-tests = { path = "packages/tests/shared" }

# WAVS
wavs-types = { version = "0.5.3", default-features = false, features = ["cosmwasm"] }
wavs-wasi-utils = "0.5.1"

# Error handling
anyhow = "1.0.98"
thiserror = "2.0.12"

# Async
tokio = { version = "1.47.1", features = ["full"] }
async-trait = "0.1.88"
futures = "0.3.31"

# http
reqwest = { version = "0.12", features = ["json"] }

# pool management
deadpool = "0.12.2"

# hashing / cipher
sha2 = "0.10.9"
const-hex = "1.14.1"
ripemd = "0.1.3"
rustls = {version = "0.23.31", features = ["aws-lc-rs"]}

# Serialization
serde = {version = "1.0.219", features = ["derive"]}
bincode = {version = "2.0.1", features = ["serde"]}
toml = "0.9.5"
serde_json = "1.0.142"

# Layer-climb
layer-climb = "0.7.1"
layer-climb-address = {version = "0.7.1", features = ["cw-storage", "openapi"] }
layer-climb-config = "0.7.1"
layer-climb-cli = "0.7.1"

# Cosmos-specific dependencies
cosmwasm-schema = "3.0.1"
cosmwasm-std = { version = "3.0.1", features = ["staking", "stargate"] }
cw-storage-plus = "3.0.0"
cw2 = "3.0.0"
cw-multi-test = { version = "3.0.1", features = ["staking", "stargate"] }

# WASI
wstd = "0.5.3"
wit-bindgen-rt = "0.43.0"

# CLI
clap = { version = "4.5.44", features = ["derive", "env", "string"] }
dotenvy = "0.15.7"

# Randomness
rand = {version = "0.9.2"}

# Alloy
alloy-primitives = "1.3.0"
alloy-sol-macro = "1.3.0"
alloy-sol-types = "1.3.0"

# Logging
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"] }
