# This is mostly just a convenience to start common tasks from the root directory
version: "3"

# silent: true

dotenv: [".env"]

includes:
  contract: ./taskfile/contract.yml
  component: ./taskfile/component.yml
  backend: ./taskfile/backend.yml
  cli: ./taskfile/cli.yml
  e2e: ./taskfile/e2e.yml

tasks:
  default:
    cmds:
      - task --list-all