version: "3"

vars:
  REPO_ROOT:
    # find the root directory of the repository by looking for the `.git` directory.
    sh: git rev-parse --show-toplevel
  BACKEND_DIR: '{{joinPath .REPO_ROOT "backend"}}'
  WAVS_HOME_DIR: '{{joinPath .BACKEND_DIR "wavs-home"}}'
  COMPONENT_EXEC_LOG_LEVEL: 'info'